# Generated by Django 5.1.7 on 2025-03-18 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.category'),
        ),
    ]
